name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-evolife:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './evolife/package-lock.json'
      
      - name: Update dependencies
        working-directory: ./evolife
        run: npm install
      
      - name: Install dependencies
        working-directory: ./evolife
        run: npm ci
      
      - name: Build
        working-directory: ./evolife
        run: npm run build

      - name: Upload evolife artifact
        uses: actions/upload-artifact@v4
        with:
          name: evolife-build
          path: './evolife/dist'
          retention-days: 1

  build-roguelike:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './roguelike/package-lock.json'
      
      - name: Update dependencies
        working-directory: ./roguelike
        run: npm install
      
      - name: Install dependencies
        working-directory: ./roguelike
        run: npm ci
      
      - name: Build
        working-directory: ./roguelike
        run: npm run build

      - name: Upload roguelike artifact
        uses: actions/upload-artifact@v4
        with:
          name: roguelike-build
          path: './roguelike/dist'
          retention-days: 1

  build-gakuensai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './gakuensai/package-lock.json'
      
      - name: Update dependencies
        working-directory: ./gakuensai
        run: npm install
      
      - name: Install dependencies
        working-directory: ./gakuensai
        run: npm ci
      
      - name: Build
        working-directory: ./gakuensai
        run: npm run build

      - name: Upload gakuensai artifact
        uses: actions/upload-artifact@v4
        with:
          name: gakuensai-build
          path: './gakuensai/dist'
          retention-days: 1

  build-menu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload menu artifact
        uses: actions/upload-artifact@v4
        with:
          name: menu-build
          path: './menu'
          retention-days: 1

  build-shiritori:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './shiritori/package-lock.json'
      
      - name: Update dependencies
        working-directory: ./shiritori
        run: npm install
      
      - name: Install dependencies
        working-directory: ./shiritori
        run: npm ci
      
      - name: Build
        working-directory: ./shiritori
        run: npm run build

      - name: Upload shiritori artifact
        uses: actions/upload-artifact@v4
        with:
          name: shiritori-build
          path: './shiritori/dist'
          retention-days: 1

  build-suiko-sts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './suiko_sts/package-lock.json'
      
      - name: Update dependencies
        working-directory: ./suiko_sts
        run: npm install
      
      - name: Install dependencies
        working-directory: ./suiko_sts
        run: npm ci
      
      - name: Build
        working-directory: ./suiko_sts
        run: npm run build

      - name: Upload suiko-sts artifact
        uses: actions/upload-artifact@v4
        with:
          name: suiko-sts-build
          path: './suiko_sts/dist'
          retention-days: 1

  deploy:
    needs: [build-evolife, build-roguelike, build-gakuensai, build-menu, build-shiritori, build-suiko-sts]
    environment:
      name: github-pages
      url: ${{ github.io_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download evolife build
        uses: actions/download-artifact@v4
        with:
          name: evolife-build
          path: './dist/evolife'

      - name: Download roguelike build
        uses: actions/download-artifact@v4
        with:
          name: roguelike-build
          path: './dist/roguelike'

      - name: Download gakuensai build
        uses: actions/download-artifact@v4
        with:
          name: gakuensai-build
          path: './dist/gakuensai'

      - name: Download shiritori build
        uses: actions/download-artifact@v4
        with:
          name: shiritori-build
          path: './dist/shiritori'

      - name: Download suiko-sts build
        uses: actions/download-artifact@v4
        with:
          name: suiko-sts-build
          path: './dist/suiko_sts'

      - name: Download menu build
        uses: actions/download-artifact@v4
        with:
          name: menu-build
          path: './dist'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4